Bookers2/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :books
  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
  delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
  resources :books do
  	resources :book_comments, only: [:create, :destroy]
  end
  get "home/about" => "home#about"
end

Bookers2/app/models/book.rb
class Book < ApplicationRecord

	belongs_to :user, optional: true
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200 }
end

Bookers2/app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

Bookers2/app/models/favorite.rb
class Favorite < ApplicationRecord

	belongs_to :user
	belongs_to :book
end

Bookers2/app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :following, class_name: "User"
	validates :follower_id, presence:true
	validates :following_id, presence:true
end

Bookers2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_books, through: :favorites
  has_many :book_comments, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
  def favorited_by?(book_id)
  	favorites.where(book_id: book_id).exists?
  end

  has_many :following_relationships, foreign_key: "follower_id", 
            class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", 
            class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def follow(other_user)
    following_relationships.create(following_id: other_user.id)
  end

  def unfollow(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end
end

Bookers2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
    	user_path(resource.id)
  	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
	end
end

Bookers2/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	before_action :authenticate_user!, only: [:create, :destroy]
	before_action :correct_user, only: [:destroy]
	def create
		book = Book.find(params[:book_id])
		@book_comment = book.book_comments.build(book_comment_params)
		# @book_comment = BookComment.new(book_comment_params)
		# @book_comment.book_id = book.id
		@book_comment.user_id = current_user.id
    	if @book_comment.save
    	redirect_back(fallback_location: root_path)
    	else
    	redirect_back(fallback_location: root_path)
    	end
	end

	def destroy
		@book_comment.destroy
		redirect_back(fallback_location: root_path)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end

	def correct_user
    @book_comment = current_user.book_comments.find_by(id: params[:id])
    unless @book_comment
      redirect_to books_path
    end
  end
end

Bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]

	def index
		@books = Book.all
    	@book = Book.new
    	@user = current_user
	end

	def show
		@book = Book.find(params[:id])
		@book_comment = BookComment.new
		@book_comments = @book.book_comments
	end

	def create
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
		redirect_to book_path(@book), notice: "You have creatad book successfully."
		else
		@books = Book.all
		@user = current_user
		render 'index'
		end
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
	  	@book = Book.find(params[:id])
	  	@book.user_id = current_user.id
	  	if @book.update(book_params)
	  	redirect_to book_path(@book), notice: "You have updated book successfully."
	    else
	      render 'edit'
	    end
  	end

	def destroy
		@book = Book.find(params[:id])
	  	@book.destroy
	  	redirect_to books_path
  	end

  	private
  	def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  	end

  	def correct_user
  		@book = Book.find(params[:id])
  		unless current_user.id == @book.user_id then
  			redirect_to books_path
  		end
    end
end

Bookers2/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	 before_action :authenticate_user!, only: [:create, :destroy]
	def create
		Favorite.create(user_id: current_user.id, book_id: params[:id])
		redirect_back(fallback_location: root_path)
	end

	def destroy
		Favorite.find_by(user_id: current_user.id, book_id: params[:id]).destroy
		redirect_back(fallback_location: root_path)
	end
end

Bookers2/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	def about
	end
end

Bookers2/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

	def create
    	@user = User.find(params[:relationship][:following_id])
    	current_user.follow(@user)
    	redirect_back(fallback_location: root_path)
  	end

  	def destroy
    	@user = Relationship.find(params[:id]).following
    	current_user.unfollow(@user)
    	redirect_back(fallback_location: root_path)
  	end
end

Bookers2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
	  @book = Book.new
  end

  def edit
  	@user = current_user
  end

  def update
  	@user = current_user
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render 'edit'
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
	params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def correct_user
    @user = User.find(params[:id])
    unless current_user == @user then
      redirect_to user_path(current_user.id)
    end
  end
end

Bookers2/app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

Bookers2/app/helpers/favorites_helper.rb
module FavoritesHelper
end

Bookers2/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

Bookers2/app/views/home/about.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-6 col-md-offset-3">
	<h1>Welcome to <i class="fas fa-book"></i>Bookers !!</h1>
  </div>
</div>

Bookers2/app/views/home/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class="row">
  	<div class="col-md-6 col-md-offset-3">
	<h1>Welcome to <i class="fas fa-book"></i>Bookers !!</h1>
	<h5>In <i class="fas fa-book"></i>Bookers,</h5>
	<p>you can share and exchange your opinions , inpressions , and emotions</br>about various books!</p>

	<%= link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %>
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1"%>
	</div>
  </div>
</div>

Bookers2/app/views/users/_list.html.erb
<h1>User info</h1>
 <%= attachment_image_tag user, :profile_image, size: "100x100", format: 'jpeg', fallback: "no_image.jpg" %>


<table class="table">
	<tbody>
		<tr></tr>
		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>
		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>
		<tr>
			<th>Follows</th>
			<th>
				<%= link_to following_user_path(user) do %>
				<strong>
      			<%= user.followings.count %>
    			</strong>
    			<% end %>
			</th>
		</tr>
		<tr>
			<th>Followers</th>
			<th>
				<%= link_to followers_user_path(user) do %>
				<strong>
      			<%= user.followers.count %>
    			</strong>
    			<% end %>
			</th>
		</tr>
	</tbody>
</table>
		<% unless current_user == user %>
			<% if current_user.following?(user) %>
				<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
				<%= f.submit "フォロー外す", class: "btn btn-large btn-primary follow-btn" %>
			<% end %>
			<% else %>
	 			<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
	   			<%= f.hidden_field :following_id %>
	   			<%= f.submit "フォローする", class: "btn btn-large btn-success follow-btn" %>
	    	<% end %>
	   		<% end %>
	    <% end %>

	<div class="row">
	<% if user.id == current_user.id %>
        <%= link_to edit_user_path(user) do %>
        <span class="glyphicon glyphicon-wrench btn btn-default col-xs-11"></span>
        <% end %>
    <% end %>
	</div>
<div class="row">
<h2>New book</h2>
</div>
<div class="row">
<%= form_for(book) do |f| %>
	<% if book.errors.any? %>
		<p><%= book.errors.count %> error prohibited this book from being saved:</p>
		<ul>
			<% book.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<div class="row">
<h3>Title</h3>
</div>
<div class="row">
	<%= f.text_field :title, class: "col-xs-11" %>
</div>
<div class="row">
<h3>opinion</h3>
</div>

<div class="row">
	<%= f.text_area :body, class: "col-xs-11" %>
</div>

<div class="row">
<br><%= f.submit 'Create Book', class: "btn btn-primary col-xs-11" %></br>
</div>
<% end %>
</div>

Bookers2/app/views/users/_stats.html.erb
 
 <% @user ||= current_user %>
<div class="stats">
  <a href=<%= following_user_path(@user) %>>
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href=<%= followers_user_path(@user) %>>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

Bookers2/app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
<h1>User info</h1>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
		<p><%= @user.errors.count %> errors prohibited this obj from being saved:</p>
		<ul>
			<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
			<% end %>
		</ul>
	<% end %>
<h4>Name</h4><%= f.text_field :name %>
<h4>Image</h4>
<%= f.attachment_field :profile_image, class: "user-edit-form" %>
<h4>Introduction</h4>
<%= f.text_area :introduction %>
<br><%= f.submit 'Update User' %></br>
<% end %>
</div>
</div>
</div>

Bookers2/app/views/users/index.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class="row">
  <div class="col-xs-3">
  <%= render 'users/list', book: @book, user: @user %>
</div>

<div class="col-xs-9">
<h1>Users</h1>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>
			<td><%= link_to "Show", user_path(user.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>

Bookers2/app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>

<div class="container">
  <div class="row">
  <div class="col-xs-3">
<%= render 'users/list', book: @book, user: @user %>
</div>

<div class="col-xs-9">
<h1>Books</h1>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
		</tr>
	</thead>
	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td><%= link_to (@book.user) do %>
				<%= attachment_image_tag book.user, :profile_image, size: "60x60", format: 'jpeg', fallback: "no_image.jpg" %>
				<% end %>
			</td>
			<td><%= link_to book_path(book) do %>
				<%= book.title %>
				<% end %>
			</td>
			<td><%= book.body %></td>
			<td>
				コメント数: <%= book.book_comments.count %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>
</div>

Bookers2/app/views/users/show_follow.html.erb
<div class="container">
<div class="row">
<h1>Follow Users</h1>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @user.followings.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>
			<td>フォロー数: <%= user.followings.count %></td>
			<td>フォロワー数: <%= user.followers.count %></td>
			<td>
				<% unless current_user == user %>
					<% if current_user.following?(user) %>
						<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
						<%= f.submit "フォロー外す", class: "btn-link" %>
						<% end %>
					<% else %>
	 					<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
	   					<%= f.hidden_field :following_id %>
	   					<%= f.submit "フォローする", class: "btn-link" %>
	    				<% end %>
	   				<% end %>
	    		<% end %>
			</td>
			<td><%= link_to "Show", user_path(user.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>

Bookers2/app/views/users/show_follower.html.erb
<div class="container">
<div class="row">
<h1>Follower Users</h1>
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @user.followers.each do |user| %>
		<tr>
			<td><%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', fallback: "no_image.jpg" %></td>
			<td><%= user.name %></td>
			<td>フォロー数: <%= user.followings.count %></td>
			<td>フォロワー数: <%= user.followers.count %></td>
			<td>
				<% unless current_user == user %>
					<% if current_user.following?(user) %>
						<%= form_for(current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete }) do |f| %>
						<%= f.submit "フォロー外す", class: "btn-link" %>
						<% end %>
					<% else %>
	 					<%= form_for(current_user.following_relationships.build(following_id: user.id)) do |f| %>
	   					<%= f.hidden_field :following_id %>
	   					<%= f.submit "フォローする", class: "btn-link" %>
	    				<% end %>
	   				<% end %>
	    		<% end %>
			</td>
			<td><%= link_to "Show", user_path(user.id) %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</div>
</div>